wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.23
    start_time: 1766643477
    t:
      1:
      - 1
      - 11
      3:
      - 13
      4: 3.9.23
      5: 0.12.10
      6: 4.34.0
      8:
      - 5
