name: aslora
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libcblas=3.11.0=4_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=4_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - python_abi=3.9=8_cp39
  - readline=8.2=h8c095d6_2
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - tensorly=0.8.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - accelerate==0.30.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - cachetools==6.2.3
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - datasets==2.14.7
      - decorator==5.2.1
      - deepspeed==0.15.4
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fairscale==0.4.5
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2023.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.17.3
      - idna==3.11
      - importlib-metadata==8.7.0
      - ipython==8.14.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - markdown==3.9
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - modelscope==1.33.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.15
      - networkx==3.2.1
      - ninja==1.11.1.2
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.3.1
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - promise==2.3
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==3.20.3
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - rouge-score==0.1.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - sentencepiece==0.1.96
      - sentry-sdk==2.47.0
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - tokenizers==0.14.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.34.0
      - triton==3.2.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - wandb==0.12.10
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - xxhash==3.6.0
      - yarl==1.22.0
      - yaspin==3.3.0
      - zipp==3.23.0
prefix: /home/dengkn/miniforge3/envs/aslora
